"""Generate Tables 1-4, Figures 1-8, and unaggregated run data.

Every experiment is read from a JSON manifest. The manuscript manifest uses
the reported run/period counts; the smoke manifest uses the same code paths
with smaller counts for CI. Outputs are never treated as historical v3.2 data:
they are regenerated by the corrected, specification-aligned implementation.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import asdict
from pathlib import Path
from typing import Any, Iterable, Sequence
import argparse
import json
import math
import shutil
import zlib

import numpy as np

from simulation_pkd_v32 import (
    BASELINE_SYSTEMS,
    ModelConfig,
    RunResult,
    SYSTEM_APPEAL,
    SYSTEM_PKD,
    SYSTEM_RETROSPECTIVE,
    SYSTEM_SCORE_INFORMED,
    SYSTEM_SORTITION,
    SYSTEM_SORTITION_DELIBERATION,
    export_run_data,
    run_ensemble,
    run_simulation,
    summarize_runs,
    write_csv,
)


def _slug(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "_" for ch in value).strip("_")


def _seed(base_seed: int, label: str) -> int:
    return int(np.uint32(base_seed) ^ np.uint32(zlib.crc32(label.encode("utf-8"))))


def _mean_ci(values: Sequence[float]) -> tuple[float, float, float]:
    array = np.asarray(values, dtype=float)
    mean = float(array.mean())
    if len(array) < 2:
        return mean, mean, mean
    se = float(array.std(ddof=1) / math.sqrt(len(array)))
    try:
        from scipy import stats

        critical = float(stats.t.ppf(0.975, len(array) - 1))
    except ImportError:
        critical = 1.96
    return mean, mean - critical * se, mean + critical * se


def _run_means(results: Sequence[RunResult]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in summarize_runs(results):
        grouped[str(row["system"])].append(row)
    return grouped


def _aggregate(results: Sequence[RunResult]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for system, system_rows in sorted(_run_means(results).items()):
        mean, low, high = _mean_ci([row["mean_performance"] for row in system_rows])
        pre = float(np.mean([row["pre_shock_performance"] for row in system_rows]))
        post = float(np.mean([row["post_shock_performance"] for row in system_rows]))
        infiltration = float(
            np.mean([row["mean_demagogue_fraction"] for row in system_rows])
        )
        rows.append(
            {
                "system": system,
                "mean_performance": mean,
                "ci95_low": low,
                "ci95_high": high,
                "pre_shock_performance": pre,
                "post_shock_performance": post,
                "post_minus_pre": post - pre,
                "mean_demagogue_fraction": infiltration,
                "n_runs": len(system_rows),
            }
        )
    return rows


def _trajectory(
    results: Sequence[RunResult], system: str, field: str = "performance"
) -> np.ndarray:
    trajectories = []
    for result in results:
        records = result.system_periods(system)
        trajectories.append([getattr(record, field) for record in records])
    return np.asarray(trajectories, dtype=float)


class Reproducer:
    def __init__(self, manifest_path: Path, output_dir: Path):
        self.manifest_path = manifest_path
        self.output_dir = output_dir
        with manifest_path.open("r", encoding="utf-8") as handle:
            self.manifest = json.load(handle)
        self.base = ModelConfig.from_mapping(self.manifest["model"])
        self.base_seed = int(self.manifest["base_seed"])
        self.raw_dir = output_dir / "raw"
        self.tables_dir = output_dir / "tables"
        self.figures_dir = output_dir / "figures"
        self.artifacts: list[dict[str, Any]] = []
        for directory in (self.raw_dir, self.tables_dir, self.figures_dir):
            directory.mkdir(parents=True, exist_ok=True)
        shutil.copy2(manifest_path, output_dir / "resolved_experiment_manifest.json")

    def run_condition(
        self,
        label: str,
        config: ModelConfig,
        n_runs: int,
        *,
        export: bool = True,
    ) -> list[RunResult]:
        results = run_ensemble(
            config,
            n_runs=int(n_runs),
            base_seed=_seed(self.base_seed, label),
        )
        if export:
            export_run_data(results, self.raw_dir / _slug(label))
        return results

    def table(self, number: int, filename: str, rows: Iterable[dict[str, Any]]) -> None:
        path = self.tables_dir / filename
        write_csv(path, rows)
        self.artifacts.append(
            {
                "artifact": f"Table {number}",
                "path": path.relative_to(self.output_dir).as_posix(),
                "generator": "reproduce_all.py",
                "raw_inputs": "raw/baseline",
            }
        )

    def save_figure(self, number: int, figure, stem: str, raw_inputs: str) -> None:
        png = self.figures_dir / f"{stem}.png"
        pdf = self.figures_dir / f"{stem}.pdf"
        figure.savefig(png, dpi=300, bbox_inches="tight")
        figure.savefig(pdf, bbox_inches="tight")
        self.artifacts.append(
            {
                "artifact": f"Figure {number}",
                "path": png.relative_to(self.output_dir).as_posix(),
                "generator": "reproduce_all.py",
                "raw_inputs": raw_inputs,
            }
        )

    def baseline(self) -> list[RunResult]:
        spec = self.manifest["experiments"]["baseline"]
        config = self.base.with_updates(
            n_periods=int(spec["periods"]), include_sortition_deliberation=True
        )
        results = self.run_condition("baseline", config, int(spec["runs"]))
        aggregates = _aggregate(results)
        table1 = [row for row in aggregates if row["system"] in BASELINE_SYSTEMS]
        self.table(1, "table1_baseline.csv", table1)

        archetypes: dict[str, list[Any]] = defaultdict(list)
        for result in results:
            for agent in result.agents:
                archetypes[agent.archetype].append(agent)
        table2 = []
        for archetype, agents in sorted(archetypes.items()):
            table2.append(
                {
                    "archetype": archetype,
                    "mean_track_record": float(
                        np.mean([agent.track_record for agent in agents])
                    ),
                    "mean_tolerance": float(np.mean([agent.tolerance for agent in agents])),
                    "n_agent_runs": len(agents),
                }
            )
        self.table(2, "table2_track_records.csv", table2)

        current = {row["system"]: row for row in aggregates}
        docking_rows = []
        for source, systems in self.manifest.get("docking_reference", {}).items():
            for system, values in systems.items():
                docking_rows.append({"source": source, "system": system, **values})
        for system, row in current.items():
            docking_rows.append(
                {
                    "source": "corrected_specification_run",
                    "system": system,
                    "mean_performance": row["mean_performance"],
                    "post_minus_pre": row["post_minus_pre"],
                    "mean_demagogue_fraction": row["mean_demagogue_fraction"],
                    "status": "regenerated",
                }
            )
        self.table(3, "table3_model_docking.csv", docking_rows)

        grouped = _run_means(results)
        pkd_by_run = {int(row["run"]): float(row["mean_performance"]) for row in grouped[SYSTEM_PKD]}
        table4 = []
        for comparison in (
            SYSTEM_SORTITION,
            SYSTEM_SORTITION_DELIBERATION,
            SYSTEM_APPEAL,
            "Autocracy",
        ):
            comparison_by_run = {
                int(row["run"]): float(row["mean_performance"])
                for row in grouped[comparison]
            }
            runs = sorted(set(pkd_by_run) & set(comparison_by_run))
            differences = np.array(
                [pkd_by_run[index] - comparison_by_run[index] for index in runs]
            )
            mean, low, high = _mean_ci(differences)
            sd = float(differences.std(ddof=1)) if len(differences) > 1 else 0.0
            t_stat = mean / (sd / math.sqrt(len(differences))) if sd else math.inf
            p_paired: float | str = ""
            p_wilcoxon: float | str = ""
            try:
                from scipy import stats

                p_paired = float(stats.ttest_rel(
                    [pkd_by_run[index] for index in runs],
                    [comparison_by_run[index] for index in runs],
                ).pvalue)
                p_wilcoxon = float(stats.wilcoxon(differences).pvalue)
            except ImportError:
                pass
            table4.append(
                {
                    "comparison": f"PKD vs {comparison}",
                    "mean_paired_difference": mean,
                    "ci95_low": low,
                    "ci95_high": high,
                    "paired_t": t_stat,
                    "p_paired_t": p_paired,
                    "p_wilcoxon": p_wilcoxon,
                    "cohens_dz": mean / sd if sd else math.inf,
                    "n_pairs": len(differences),
                }
            )
        self.table(4, "table4_paired_inference.csv", table4)
        return results

    def figures_1_and_2(self, baseline: Sequence[RunResult]) -> None:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        single_seed = int(self.manifest["experiments"]["baseline"]["single_seed"])
        single = run_simulation(baseline[0].config, seed=single_seed, run=0)
        export_run_data([single], self.raw_dir / "figure1_single_run")
        colors = {
            "Autocracy": "#777777",
            SYSTEM_APPEAL: "#d1495b",
            SYSTEM_SORTITION: "#3a86a8",
            SYSTEM_PKD: "#2a9d5b",
        }

        fig, axes = plt.subplots(2, 3, figsize=(16, 9))
        for system in BASELINE_SYSTEMS:
            values = _trajectory([single], system)[0]
            axes[0, 0].plot(values, label=system, color=colors[system], lw=1)
            axes[0, 1].plot(np.cumsum(values), label=system, color=colors[system], lw=1.5)
            infiltration = _trajectory([single], system, "demagogue_fraction")[0]
            axes[0, 2].step(
                np.arange(len(infiltration)), infiltration, where="post",
                label=system, color=colors[system], lw=1.2,
            )
        for axis in axes[0]:
            axis.axvline(single.config.shock_period, color="black", ls="--", lw=0.8)
            axis.grid(alpha=0.2)
        axes[0, 0].set_title("A. Per-period performance")
        axes[0, 1].set_title("B. Cumulative performance")
        axes[0, 2].set_title("C. Demagogue council share")

        by_arch: dict[str, list[float]] = defaultdict(list)
        for agent in single.agents:
            by_arch[agent.archetype].append(agent.track_record)
        axes[1, 0].boxplot(list(by_arch.values()), tick_labels=list(by_arch))
        axes[1, 0].set_title("D. Final track records")
        top_agents = sorted(single.agents, key=lambda agent: agent.track_record, reverse=True)[
            : single.config.n_expert_seats
        ]
        axes[1, 1].bar(
            [str(agent.agent_id) for agent in top_agents],
            [agent.tolerance for agent in top_agents],
            color="#5c677d",
        )
        axes[1, 1].set_title("E. Tolerance of final top-score agents")
        summary = {row["system"]: row for row in _aggregate([single])}
        axes[1, 2].axis("off")
        cell_text = [
            [system, f"{summary[system]['mean_performance']:.3f}",
             f"{summary[system]['mean_demagogue_fraction']:.1%}"]
            for system in BASELINE_SYSTEMS
        ]
        axes[1, 2].table(
            cellText=cell_text,
            colLabels=["System", "Mean", "Demagogue"],
            loc="center",
            cellLoc="center",
        )
        axes[1, 2].set_title("F. Run summary")
        handles, labels = axes[0, 0].get_legend_handles_labels()
        fig.legend(handles, labels, loc="lower center", ncol=4, fontsize=8)
        fig.tight_layout(rect=(0, 0.05, 1, 1))
        self.save_figure(1, fig, "figure1_single_run", "raw/figure1_single_run")
        plt.close(fig)

        fig, axes = plt.subplots(1, 3, figsize=(16, 4.8))
        for system in BASELINE_SYSTEMS:
            values = _trajectory(baseline, system)
            mean = values.mean(axis=0)
            ci = 1.96 * values.std(axis=0, ddof=1) / math.sqrt(len(values))
            axes[0].plot(mean, label=system, color=colors[system])
            axes[0].fill_between(np.arange(len(mean)), mean - ci, mean + ci,
                                 color=colors[system], alpha=0.15)
            axes[1].plot(np.cumsum(mean), label=system, color=colors[system])
            infiltration = _trajectory(baseline, system, "demagogue_fraction")
            axes[2].plot(infiltration.mean(axis=0), label=system, color=colors[system])
        for axis in axes:
            axis.axvline(baseline[0].config.shock_period, color="black", ls="--", lw=0.8)
            axis.grid(alpha=0.2)
        axes[0].set_title("A. Mean performance (95% CI)")
        axes[1].set_title("B. Cumulative mean")
        axes[2].set_title("C. Mean demagogue share")
        axes[0].legend(fontsize=7)
        fig.tight_layout()
        self.save_figure(2, fig, "figure2_ensemble", "raw/baseline")
        plt.close(fig)

    def sensitivity(self) -> list[dict[str, Any]]:
        spec = self.manifest["experiments"]["sensitivity"]
        rows: list[dict[str, Any]] = []
        for parameter, values in spec["grids"].items():
            for value in values:
                updates: dict[str, Any] = {"n_periods": int(spec["periods"])}
                if parameter == "demagogue_fraction":
                    n_demagogues = int(round(self.base.population_size * float(value)))
                    updates.update(
                        n_demagogues=n_demagogues,
                        n_citizens=self.base.population_size
                        - self.base.n_experts
                        - n_demagogues,
                    )
                elif parameter == "seats_per_pool":
                    seats = int(value)
                    updates.update(
                        n_expert_seats=seats,
                        n_citizen_seats=seats,
                        sortition_size=2 * seats,
                    )
                else:
                    updates[parameter] = value
                config = self.base.with_updates(**updates)
                label = f"sensitivity_{parameter}_{value}"
                results = self.run_condition(label, config, int(spec["runs"]))
                for row in _aggregate(results):
                    rows.append(
                        {
                            "parameter": parameter,
                            "value": value,
                            "system": row["system"],
                            "mean_performance": row["mean_performance"],
                            "ci95_low": row["ci95_low"],
                            "ci95_high": row["ci95_high"],
                            "mean_demagogue_fraction": row[
                                "mean_demagogue_fraction"
                            ],
                        }
                    )
        write_csv(self.raw_dir / "figure3_sensitivity.csv", rows)

        import matplotlib.pyplot as plt

        parameters = list(spec["grids"])
        fig, axes = plt.subplots(2, 4, figsize=(17, 8))
        for axis, parameter in zip(axes.flat, parameters):
            subset = [row for row in rows if row["parameter"] == parameter]
            for system in (SYSTEM_APPEAL, SYSTEM_SORTITION, SYSTEM_PKD):
                system_rows = [row for row in subset if row["system"] == system]
                axis.plot(
                    [float(row["value"]) for row in system_rows],
                    [row["mean_performance"] for row in system_rows],
                    marker="o", label=system,
                )
            axis.set_title(parameter.replace("_", " "))
            axis.grid(alpha=0.2)
        axes.flat[-1].axis("off")
        axes.flat[0].legend(fontsize=7)
        fig.tight_layout()
        self.save_figure(3, fig, "figure3_sensitivity", "raw/sensitivity_*")
        plt.close(fig)

        fraction_rows = [row for row in rows if row["parameter"] == "demagogue_fraction"]
        fig, axis = plt.subplots(figsize=(7, 5))
        for system in BASELINE_SYSTEMS:
            system_rows = [row for row in fraction_rows if row["system"] == system]
            axis.plot(
                [float(row["value"]) for row in system_rows],
                [row["mean_demagogue_fraction"] for row in system_rows],
                marker="o", label=system,
            )
        axis.plot([0, 0.3], [0, 0.3], color="black", ls="--", label="population share")
        axis.set_xlabel("Demagogue population fraction")
        axis.set_ylabel("Council fraction")
        axis.grid(alpha=0.2)
        axis.legend(fontsize=7)
        fig.tight_layout()
        self.save_figure(4, fig, "figure4_infiltration", "raw/sensitivity_demagogue_fraction_*")
        plt.close(fig)
        return rows

    def bias_sweep(self) -> None:
        spec = self.manifest["experiments"]["bias_sweep"]
        rows = []
        for value in spec["values"]:
            config = self.base.with_updates(
                n_periods=int(spec["periods"]), demagogue_bias_norm=float(value)
            )
            results = self.run_condition(
                f"bias_{value}", config, int(spec["runs"])
            )
            for row in _aggregate(results):
                rows.append({"bias_norm": value, **row})
        write_csv(self.raw_dir / "figure5_bias_sweep.csv", rows)
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(1, 2, figsize=(11, 4.5))
        for system in (SYSTEM_APPEAL, SYSTEM_SORTITION, SYSTEM_PKD):
            subset = [row for row in rows if row["system"] == system]
            x = [float(row["bias_norm"]) for row in subset]
            axes[0].plot(x, [row["mean_performance"] for row in subset], marker="o", label=system)
            axes[1].plot(x, [row["mean_demagogue_fraction"] for row in subset], marker="o", label=system)
        axes[0].set_title("A. Performance")
        axes[1].set_title("B. Demagogue share")
        for axis in axes:
            axis.set_xlabel("Demagogue bias norm")
            axis.grid(alpha=0.2)
        axes[0].legend(fontsize=7)
        fig.tight_layout()
        self.save_figure(5, fig, "figure5_bias_sweep", "raw/bias_*")
        plt.close(fig)

    def scoring_channel(self) -> None:
        spec = self.manifest["experiments"]["scoring_channel"]
        rows = []
        mapping = {
            "proxy_noise": "proxy_noise",
            "feedback_delay": "feedback_delay",
            "scored_dimensions": "scored_dimensions",
        }
        for axis_name, field in mapping.items():
            for value in spec[axis_name]:
                config = self.base.with_updates(
                    n_periods=int(spec["periods"]), **{field: value}
                )
                results = self.run_condition(
                    f"scoring_{axis_name}_{value}", config, int(spec["runs"])
                )
                for row in _aggregate(results):
                    rows.append({"axis": axis_name, "value": value, **row})
        write_csv(self.raw_dir / "figure6_scoring_channel.csv", rows)
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(2, 2, figsize=(12, 8))
        proxy = [row for row in rows if row["axis"] == "proxy_noise"]
        for system in (SYSTEM_APPEAL, SYSTEM_SORTITION, SYSTEM_PKD):
            subset = [row for row in proxy if row["system"] == system]
            x = [float(row["value"]) for row in subset]
            axes[0, 0].plot(x, [row["mean_performance"] for row in subset], marker="o", label=system)
            axes[0, 1].plot(x, [row["mean_demagogue_fraction"] for row in subset], marker="o", label=system)
        for axis, axis_name, title in (
            (axes[1, 0], "feedback_delay", "C. Feedback delay"),
            (axes[1, 1], "scored_dimensions", "D. Scored dimensions"),
        ):
            for system in (SYSTEM_SORTITION, SYSTEM_PKD):
                subset = [row for row in rows if row["axis"] == axis_name and row["system"] == system]
                axis.plot(
                    [float(row["value"]) for row in subset],
                    [row["mean_performance"] for row in subset],
                    marker="o", label=system,
                )
            axis.set_title(title)
        axes[0, 0].set_title("A. Proxy noise: performance")
        axes[0, 1].set_title("B. Proxy noise: demagogue share")
        axes[0, 0].legend(fontsize=7)
        for axis in axes.flat:
            axis.grid(alpha=0.2)
        fig.tight_layout()
        self.save_figure(6, fig, "figure6_scoring_channel", "raw/scoring_*")
        plt.close(fig)

    def appeal_feedback(self) -> None:
        spec = self.manifest["experiments"]["appeal_feedback"]
        rows = []
        for proxy in spec["proxy_noise"]:
            for weight in spec["retrospective_weights"]:
                config = self.base.with_updates(
                    n_periods=int(spec["periods"]),
                    proxy_noise=float(proxy),
                    retrospective_weight=float(weight),
                )
                results = self.run_condition(
                    f"retrospective_proxy_{proxy}_weight_{weight}",
                    config,
                    int(spec["runs"]),
                )
                for row in _aggregate(results):
                    if row["system"] in {SYSTEM_RETROSPECTIVE, SYSTEM_PKD, SYSTEM_SORTITION}:
                        rows.append(
                            {
                                "variant": "collective_retrospective",
                                "proxy_noise": proxy,
                                "weight": weight,
                                **row,
                            }
                        )
            for weight in spec["score_informed_weights"]:
                config = self.base.with_updates(
                    n_periods=int(spec["periods"]),
                    proxy_noise=float(proxy),
                    score_informed_weight=float(weight),
                )
                results = self.run_condition(
                    f"score_informed_proxy_{proxy}_weight_{weight}",
                    config,
                    int(spec["runs"]),
                )
                for row in _aggregate(results):
                    if row["system"] == SYSTEM_SCORE_INFORMED:
                        rows.append(
                            {
                                "variant": "score_informed",
                                "proxy_noise": proxy,
                                "weight": weight,
                                **row,
                            }
                        )
        write_csv(self.raw_dir / "figure7_appeal_feedback.csv", rows)
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(1, 2, figsize=(12, 4.8))
        for variant, system, marker in (
            ("collective_retrospective", SYSTEM_RETROSPECTIVE, "o"),
            ("score_informed", SYSTEM_SCORE_INFORMED, "s"),
        ):
            for proxy in spec["proxy_noise"]:
                subset = [
                    row for row in rows
                    if row["variant"] == variant
                    and row["system"] == system
                    and float(row["proxy_noise"]) == float(proxy)
                ]
                axes[0].plot(
                    [float(row["weight"]) for row in subset],
                    [row["mean_performance"] for row in subset],
                    marker=marker, label=f"{variant}, proxy={proxy}",
                )
                axes[1].plot(
                    [float(row["weight"]) for row in subset],
                    [row["mean_demagogue_fraction"] for row in subset],
                    marker=marker, label=f"{variant}, proxy={proxy}",
                )
        for axis in axes:
            axis.set_xscale("symlog", linthresh=0.05)
            axis.grid(alpha=0.2)
        axes[0].set_title("A. Performance")
        axes[1].set_title("B. Demagogue share")
        axes[0].legend(fontsize=6)
        fig.tight_layout()
        self.save_figure(7, fig, "figure7_appeal_feedback", "raw/*appeal*; raw/score_informed_*")
        plt.close(fig)

    def gaming(self) -> None:
        spec = self.manifest["experiments"]["gaming"]
        rows = []
        trajectories: dict[str, tuple[np.ndarray, np.ndarray]] = {}
        for condition in spec["conditions"]:
            label = str(condition["label"])
            config = self.base.with_updates(
                n_periods=int(spec["periods"]),
                strategic_mode=str(condition["strategic_mode"]),
                proxy_noise=float(condition.get("proxy_noise", 0.0)),
            )
            results = self.run_condition(f"gaming_{label}", config, int(spec["runs"]))
            for row in _aggregate(results):
                if row["system"] == SYSTEM_PKD:
                    rows.append({"condition": label, **row})
            trajectories[label] = (
                _trajectory(results, SYSTEM_PKD, "demagogue_fraction").mean(axis=0),
                _trajectory(results, SYSTEM_PKD).mean(axis=0),
            )
        write_csv(self.raw_dir / "figure8_gaming.csv", rows)
        import matplotlib.pyplot as plt

        fig, axes = plt.subplots(1, 2, figsize=(12, 4.8))
        for label, (infiltration, performance) in trajectories.items():
            axes[0].plot(infiltration, label=label)
            window = min(15, len(performance))
            smoothed = np.convolve(performance, np.ones(window) / window, mode="valid")
            axes[1].plot(np.arange(window - 1, len(performance)), smoothed, label=label)
        axes[0].set_title("A. PKD demagogue share")
        axes[1].set_title("B. PKD performance (rolling mean)")
        for axis in axes:
            axis.grid(alpha=0.2)
        axes[0].legend(fontsize=6)
        fig.tight_layout()
        self.save_figure(8, fig, "figure8_gaming", "raw/gaming_*")
        plt.close(fig)

    def finalize(self) -> None:
        write_csv(self.output_dir / "artifact_map.csv", self.artifacts)
        environment = {
            "python_target": self.manifest["environment"],
            "parallel_workers": 0,
            "rng": "numpy.random.Generator with named SeedSequence children",
            "score_source": "registered raw_prediction only",
            "historical_snapshot_claim": False,
        }
        with (self.output_dir / "environment.json").open("w", encoding="utf-8") as handle:
            json.dump(environment, handle, indent=2, sort_keys=True)
            handle.write("\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", type=Path, default=Path("configs/reproduce_smoke.json")
    )
    parser.add_argument("--output-dir", type=Path, default=Path("reproduction_output"))
    parser.add_argument(
        "--only",
        default="all",
        help="Comma-separated: baseline,sensitivity,bias,scoring,feedback,gaming",
    )
    args = parser.parse_args()
    selected = {item.strip() for item in args.only.split(",")}
    if "all" in selected:
        selected = {"baseline", "sensitivity", "bias", "scoring", "feedback", "gaming"}
    reproducer = Reproducer(args.manifest, args.output_dir)
    baseline: list[RunResult] | None = None
    if "baseline" in selected:
        baseline = reproducer.baseline()
        reproducer.figures_1_and_2(baseline)
    if "sensitivity" in selected:
        reproducer.sensitivity()
    if "bias" in selected:
        reproducer.bias_sweep()
    if "scoring" in selected:
        reproducer.scoring_channel()
    if "feedback" in selected:
        reproducer.appeal_feedback()
    if "gaming" in selected:
        reproducer.gaming()
    reproducer.finalize()


if __name__ == "__main__":
    main()
